### PR TITLE
Packaging enhancements

### PR DESCRIPTION
**Pull request by youtux**
This PR contains some improvements over the packaging of the project. I took the freedom of partially rewriting the setup.py script (and moving the main executable) to take advantage of the `setuptools` features to have a more maintainable project. Setuptools is now preferred over Distutils because it allows a better management of the project dependencies (in particular, if you installed the application system-wide, you can have multiple versions of `docopt` and `Pygments` and they will not interfere with the ones required by the project).

I hope you will appreciate the effort. I test as many commands as possible (e.g. all the ones in the main executable) to make sure to not break things. Also the packaged files have not changed.

See the commits for details.

### CODE REVIEW

**Comment by chrisallenlane** [comment]
@youtux, thanks very much for taking the time to do this. The project could probably use it, and I'm not a professional Python developer, so I have to lean on the community for this kind of work.

This looks like a substantive improvement, and I intend to merge it in. For the sake of minimizing merge-conflicts, I think I'll try to merge in #171 and #184 first. I'll try to budget time to address those PRs and this one this week. (Sorry for the delay - I'm incredibly busy right now, unfortunately.)

Thanks for this, and expect to see it merged soon.

**Comment by Mic92** [comment]
@chrisallenlane if you are to busy to maintain this project on your own, you might want to try the [pull-request-hack](http://felixge.de/2013/03/11/the-pull-request-hack.html)

**Comment by chrisallenlane** [comment]
Hmm... so I finally got around to merging this in, and I published this as version `v2.1.17`. However, it seems that the crowdsourced cheatcheats are not found now, when `cheat` is installed via `pip`. Unfortuantely, I'll have to roll this back.

I'm not a professional python developer. Any clues what we need to do to fix this?

Thanks!

**Comment by youtux** [comment]
I'll try to look into it!

**Comment by youtux** [comment]
I had no problems making the `sdist` distribution for PYPI for the 2.1.17 version. All the cheatsheets are correctly bundled into the package. Which version of pip do you have? Mine is `7.1.2` (`pip -V`)

**Comment by chrisallenlane** [comment]
Thanks for the prompt response despite my unreasonable delays!

So:

```
chris@fourside:~$ pip --version
pip 1.1 from /usr/lib/python2.7/dist-packages (python 2.7)
```

That could definitely be the problem. I'll try to get my system updated in the next day or two.

Also, question: up until this point, when I want to upload a new version, I've been running:

```
python setup.py sdist upload
```

Is that still correct, or is that likewise out-of-date?

Thanks!

**Comment by youtux** [comment]
> chris@fourside:~$ pip --version
> pip 1.1 from /usr/lib/python2.7/dist-packages (python 2.7)```
>
>That could definitely be the problem. I'll try to get my system updated in the next day or two.

Yeah I think that's the problem.

>Also, question: up until this point, when I want to upload a new version, I've been running:
>```python setup.py sdist upload```

Yes, it should be good.

**Pull request merged**
