### PR TITLE
Created cheatsheets for alias, cat, cp, export, kill, mv, pwd, and wc

### PR DESCRIPTION
**Pull request by shanahanjrs**

### CODE REVIEW

**Comment by chrisallenlane** [comment]
There's a lot of great stuff here. Thanks!

Question, though:

These are formatted a bit like abbreviated help menus. Most of the other cheatsheets in this project, though, are formatted more like this:

```sh
# To extract an uncompressed archive:
tar -xvf /path/to/foo.tar

# To create an uncompressed archive:
tar -cvf /path/to/foo.tar /path/to/foo/

# To extract a .gz archive:
tar -xzvf /path/to/foo.tgz
```

How would you feel about reformatting this PR to make your cheatsheets conform more closely to this established format?

**Comment by shanahanjrs** [comment]
Sure I'll go through and find some examples and reformat. Is there a style guide anywhere? If not would you want one, I'll gladly start it

**Comment by chrisallenlane** [comment]
Thanks!

As far as a style-guide goes, for the time being, please just mimic what you see in `cheat tar`.

The general format is this:

```sh
# To do the thing:
command to do the thing
```

Tonight I'll append a few notes to `CONTRIBUTING.md` indicating as much.

**Comment by shanahanjrs** [comment]
Updated!

**Comment by chrisallenlane** [comment]
Great stuff as always. These will be really appreciated by people that are new to the shell. Thanks!

**Pull request merged**
