### PR TITLE
Add cheat for running emacs in terminal

### PR DESCRIPTION
**Pull request by byxor**
A lot of people run emacs in the terminal, this small addition explains how. :ok_hand:

### CODE REVIEW

**Comment by byxor** [comment]
:white_check_mark: Approved!

**Comment by byxor** [comment]
:white_check_mark: Approved x2!

**Comment by byxor** [comment]
:white_check_mark: Approved x3!

**Comment by chrisallenlane** [comment]
Looks good. Thanks.

**Pull request merged**
