### PR TITLE
use `appdirs` to support platform depended data directories

### PR DESCRIPTION
**Pull request by brutus**
Uses `utils.get_default_data_dir` to get the default user–data directory for each platform.

This version uses [appdirs](https://github.com/ActiveState/appdirs) instead of [pyxdg](http://pyxdg.readthedocs.org/en/latest/) to support multiple platforms.

### CODE REVIEW

**Comment by chrisallenlane** [comment]
@brutus, I'm reviewing this now (slowly, as I'm not a Python developer). Sorry this has taken me so long!

Two questions:

1. Am I correct in assuming that this supercedes #184, and that may close the latter?
2. Per [an ongoing discussion][1], since you've opened this PR, `cheat` has been dual-licensed under the GPL3 and MIT licenses. With that said, are you still OK with me merging your work?

[1]: https://github.com/chrisallenlane/cheat/issues/261

**Comment by brutus** [comment]
Yes, this supercedes #184, you can close it. And I don't mind the dual licensing, fell free to merge this.

**Comment by chrisallenlane** [comment]
I hate to ask, but I'd like to trouble you with two more things, if I may:

1. Question: does `appdirs` behave in a sane way on Windows? I'm uncertain if the XDG standards currently play nicely with Windows, and I'm currently not equipped to test on that platform. (I'll try to remedy that in the next day or two.)

2. Despite what Github is saying here, when I `git diff` `brutus:appdirs` and `chrisallenlane:master`, it looks like I'm seeing a merge-conflict. Would you mind `rebase`-ing your branch against `master`?

Once we get that squared, I think we should be good to merge this in :+1:

**Comment by brutus** [comment]
On 1. I switch to `appdirs` from `pyxdg` because it _should_ support multiple platforms (acording to a post in #184 and it's [Github page](https://github.com/ActiveState/appdirs)). It worked for me on a couple of different Linux systems and I heard from a former colleague that it works on his Macbook, but I never tested it with windows. I might find someone who can test it on Win7 or XP but I don't know anyone with newer Windows systems, nor do I have access to any. Sorry about that.

On 2. Sure thing. But it will have two wait till Monday or so, cause I'm on the road right now.

**Comment by brutus** [comment]
I had some rather strange problems to cleanly rebase this branch, so I open a new pull request here: https://github.com/chrisallenlane/cheat/pull/265. As far as I'm concerned this can be closed now, cause https://github.com/chrisallenlane/cheat/pull/265 supersedes this. Sorry for the inconvenience.

**Comment by chrisallenlane** [comment]
No problem. I'll close this one in favor of #265. Thanks!

**Pull request closed without merging**
