### PR TITLE
Add the cheat sheet for pip.

### PR DESCRIPTION
**Pull request by myfavouritekk**
Add the cheat sheet for `pip`.

### CODE REVIEW

**Comment by dufferzafar** [comment]
:+1:

**Comment by chid** [comment]
`pip freeze > requirements.txt`
and 
`pip install -r requirements.txt`

are pretty useful too.

**Comment by myfavouritekk** [comment]
@chid Updated. Thanks.

**Comment by chid** [comment]
Perfect.

**Comment by chrisallenlane** [comment]
Looks great. Thanks, guys!

**Pull request merged**
