### PR TITLE
Update lsof sheet

### PR DESCRIPTION
**Pull request by dufferzafar**

### CODE REVIEW

**Comment by lucaswerkmeister** [comment]
The grammar is a bit inconsistent:

- Some examples sound like instructions: “To list all open sockets[, do this.]”
- Some are imperative: “List all …”
- And the last one is descriptive: “List**s** all …”

Perhaps you could unify this? Or at least avoid adding the third case with the last example ;)

**Comment by dufferzafar** [comment]
@lucaswerkmeister Done. Please have a look now.

**Comment by lucaswerkmeister** [comment]
Much better now, thanks!

**Comment by chrisallenlane** [comment]
Looks great. Thanks, guys!

**Pull request merged**
